export const jokeData = [
  "What do you call a rabbit with fleas? Bugs Bunny.",
  "What do you get when you pour hot water into a rabbit hole? Hot cross bunnies.",
  "What did the Easter Bunny say to the carrot? Nice gnawing you.",
  "What is Easter Bunny’s favorite kind of music? Hip-hop!",
  "What do you get if you give an Easter Bunny a pair of socks? A sock hop!",
  "How does an Easter Bunny keep his fur looking so good? Hare spray.",
  "What's the Easter Bunny's favorite restaurant? IHOP.",
  "Why was the Easter Bunny so sad? He was having a bad hare day.",
  "How does the Easter Bunny stay in shape? He eggs-ercises.",
  "How does the Easter Bunny stay fit? Hare-obics.",
  "How does the Easter Bunny travel? By hare-plane.",
  "How do you write a letter to an Easter Bunny? Use hare-mail!",
  "What do you call an Easter Bunny with a bad memory? A hare-brain!",
  "What do you call an Easter Bunny who gets kicked out of school? Egg-spelled.",
  "What the Easter Bunny’s favorite dance move? The bunny hop.",
  "What kind of bunny can't hop? A chocolate bunny.",
  "What's the Easter Bunny's favorite sport? Basket-ball.",
  "What kind of rabbit tells jokes? A funny bunny.",
  "Why couldn't the Easter Bunny watch his favorite show? Because his TV was scrambled!",
  "Did you hear about the bunny who sat on a bumblebee? It's a tender tail!",
  "Where does the Easter Bunny get his eggs? From an eggplant.",
  "What did the Easter bunny say about the Easter parade? It was eggs-cellent.",
  "What do you get if you cross Winnie the Pooh and the Easter Bunny? A honey bunny.",
];
